require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - config/**/*
    - config.ru
    - db/migrate/*
    - db/schema.rb
    - tmp/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
