name: daily-cron
on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  run:
    name: Call Exchange Rate API
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
            curl -X POST https://payreco.fly.dev/api/v1/exchange_rates \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.RAILS_API_CALL_TOKEN }}'
